version: 2

references:
base_image: &base_image
              hashicorp/terraform:light
working_directory: &working_directory
                     ~/project
default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
jobs:
  build:
    <<: *default_config

    steps:
      - checkout

      - run:
          name: Init
          command: |
            cd create-ec2
            terraform init

      - run:
          name: Format
          command: |
            cd create-ec2
            terraform fmt
  plan:
    <<: *default_config
    steps:
      - run:
          name: Plan
          command: |
            terraform plan -var-file=create-ec2/terraform.tfvars
  apply:
    <<: *default_config
    steps:
      - run:
          name: Apply
          command: |
            terraform apply -var-file=create-ec2/terraform.tfvars

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          requires:
            - approve
          filters:
            branches:
              only: master