version: 2
working_directory:
  ./create-ec2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          name: Init
          command: |
            cd create-ec2
            terraform init

      - run:
          name: Format
          command: |
            cd create-ec2
            terraform fmt

      - run:
          name: Plan
          command: |
            cd create-ec2
            terraform plan -var-file=terraform.tfvars
