version: 2
working_directory:
  ./create-ec2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light

    steps:
      - checkout

      - run:
          name: Init
          command: terraform init

      - run:
          name: Format
          command: terraform fmt

      - run:
          name: Plan
          command: terraform plan
