version: 2

references:
base_image: &base_image
              hashicorp/terraform:light
working_directory: &working_directory
                     ~/project
default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
                  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key
jobs:
  build:
    <<: *default_config

    steps:
      - checkout

      - run:
          name: Init
          command: |
            cd create-ec2
            terraform init

      - run:
          name: Format
          command: |
            cd create-ec2
            terraform fmt
  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: Plan
          command: |
            pwd
            terraform plan -var-file=cterraform.tfvars
  apply:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: Apply
          command: |
            pwd
            terraform apply -var-file=terraform.tfvars

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          requires:
            - approve
          filters:
            branches:
              only: master